FROM maven:3.8.5-openjdk17 AS build
COPY . .
RUN mvn clean -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=build/target/backendmicroservices-0.0.1-SNAPSHOT.jar backendmicroservices.jar
EXPOSE 9001
ENTRYPOINT ["java","-jar", "backendmicroservices.jar"]